[package]
name = "test-suite"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-time = { version = "0.5.0", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-16_000_000"] }

defmt = "1.0.1"
heapless = { version = "0.9.2", default-features = false }
libm = "0.2"

uwb-network-phy = { version = "0.1.0", path = "../../uwb-network-phy", features = ["defmt"] }
uwb-network-phy-dw3000 = { version = "0.1.0", path = "../../uwb-network-phy-dw3000", features = ["defmt"] }