[package]
name = "nucleo-g431rb"
version = "0.1.0"
edition = "2024"

[dependencies]
# Change stm32g431rb to your chip name, if necessary.
embassy-stm32 = { version = "0.5.0", features = [ "defmt", "time-driver-any", "stm32g431rb", "memory-x", "unstable-pac", "exti"] }
embassy-sync = { version = "0.7.2", features = ["defmt"] }
embassy-executor = { version = "0.9.1", features = ["arch-cortex-m", "executor-thread",  "executor-interrupt",  "defmt"] }
embassy-time = { version = "0.5.0", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-16_000_000"] }
embassy-futures = { version = "0.1.2" }
embassy-embedded-hal = { version = "0.5.0" }

defmt = "1.0.1"
defmt-rtt = "1.1.0"

cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
embedded-hal = { version = "1.0.0" }
embedded-hal-async = { version = "1.0.0" }
panic-probe = { version = "0.3", features = ["print-defmt"] }
heapless = { version = "0.9.2", default-features = false }
static_cell = { version = "2.1.1" }
libm = "0.2"

uwb-network-phy = { version = "0.1.0", path = "../../uwb-network-phy", features = ["defmt", "functional_tests"]}
uwb-network-phy-dw3000 = { version = "0.1.0", path = "../../uwb-network-phy-dw3000", features = ["defmt"]}
uwb-network-ranging-mac = { version = "0.1.0", path = "../../uwb-network-ranging-mac", features = ["defmt", "functional_tests"]}
test-suite = { version = "0.1.0", path = "../test-suite" }

[profile.release]
debug = 2
lto = "fat"

[features]
initiator = []