[package]
name = "uwb-network-phy-dw3000"
version = "0.1.0"
edition = "2024"
authors = ["Dan Stefanov <danstefanov.u@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
uwb-network-phy = { version = "0.1.0", path = "../uwb-network-phy" }
embedded-hal = { version = "1.0.0" }
embedded-hal-async = { version = "1.0.0" }
defmt = { version = "1.0.1", optional = true }
paste = { version = "1.0.15" }
bitflags = { version = "2.5.0" }
embassy-futures = { version = "0.1.2" }
num-complex = { version = "0.4.6", default-features = false }

[features]
defmt = ["dep:defmt", "uwb-network-phy/defmt"]